apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: fzuhelper
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /path/to/mysql/data # remember to change this

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: fzuhelper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: mysql-pv  # 绑定到指定的 PV
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: fzuhelper
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:9.0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "fzu-helper"
            - name: MYSQL_USER
              value: "fzu-helper"
            - name: MYSQL_PASSWORD
              value: "fzu-helper"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init
          hostPath:
            path: /path/to/config  # 初始化 SQL 目录 remember to change this
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fzuhelper
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
